# Generated by Django 3.0.2 on 2020-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy_table',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
