# Generated by Django 3.0.2 on 2020-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='prod_short',
            field=models.CharField(default='Short desc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='prod_vote',
            field=models.IntegerField(default=0),
        ),
    ]
